version: "3"
services:
  app:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=neXtClouD2k22
      - REDIS_HOST=redis
    ports:
      - 80
    networks:
      - frontend
      - backend
    links:
      - db
      - redis
    deploy:
      replicas: 1
#    placement:
#      constraints:
#       - node.labels.uptime == true
      resources:
        reservations:
          cpus: '0.2'
          memory: 32M
        limits:
          cpus: "4.0"
          memory: 6G
  db:
    image: mariadb
#    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  redis:
    image: redis:latest
#    restart: always
    networks:
      - frontend
    volumes:
      - redis:/var/lib/redis

volumes:
  redis:
  nextcloud:
    driver: local
    driver_opts:
      device: ':/mnt/tank/swarm/itarun/nextcloudme'
      o: 'addr=truenas.ipv9.xyz,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
      type: nfs
  db:
    driver: local
    driver_opts:
      device: ':/mnt/tank/swarm/itarun/nextclouddb'
      o: 'addr=truenas.ipv9.xyz,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
      type: nfs  

networks:
  frontend:
  backend: