version: "3"
services:
  db:
    image: mariadb
#    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  redis:
    image: redis:latest
#    restart: always
    networks:
      - frontend
    volumes:
      - redis:/var/lib/redis

  app:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.xops.ipv9.me
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASS}
      - REDIS_HOST=redis
#    ports:
#      - 80
    networks:
      - frontend
      - backend
      - webproxy
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.4'
          memory: 512M
        limits:
          cpus: "6.0"
          memory: 16G
      labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect
        - traefik.http.routers.nextcloud.tls.certresolver=default
        - traefik.http.routers.nextcloud.rule=Host(`nextcloud.xops.ipv9.me`)
        - traefik.http.routers.nextcloud.entrypoints=websecure
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
        - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://nextcloud.xops.ipv9.me
        - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' mydomain.com *.mydomain.net
        - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
        - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.nextcloud.headers.stsPreload=true
        - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
        - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/

volumes:
  redis:
  nextcloud:
    driver: local
    driver_opts:
      device: ':/mnt/tank/swarm/itarun/nextcloudme'
      o: 'addr=truenas.ipv9.xyz,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
      type: nfs
  db:
    driver: local
    driver_opts:
      device: ':/mnt/tank/swarm/itarun/nextclouddb'
      o: 'addr=truenas.ipv9.xyz,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
      type: nfs  

networks:
  frontend:
  backend:
  webproxy:
    external: true