version: "3"
services:
  app:
    image: nextcloud
  volumes:
    - nextcloud:/var/www/html
  ports:
    - 80
  networks:
    - frontend
  deploy:
    replicas: 1
#    placement:
#      constraints:
#       - node.labels.uptime == true
    resources:
      reservations:
        cpus: '0.2'
        memory: 32M
      limits:
        cpus: "2.0"
        memory: 2G
volumes:
  nextcloud:
    driver: local
    driver_opts:
      device: ':/mnt/tank/swarm/itarun/nextcloudme'
      o: 'addr=truenas.ipv9.xyz,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
      type: nfs

networks:
  frontend: